root: ''
enable_webui_interaction: true
debug: false
github_proxy: null
check_ncatbot_update: true
skip_ncatbot_install_check: false
plugin:
  plugins_dir: plugins
  plugin_whitelist: []
  plugin_blacklist: []
  load_plugin: true
  plugin_configs:
    ForwardBotPlugin: {}
bot_uin: ''
adapters:
- type: napcat
  platform: qq
  config:
    ws_uri: ws://localhost:3001
    ws_token: NcatBot
    ws_listen_ip: localhost
    webui_uri: http://localhost:6099
    webui_token: n>F,6M{&FjYitfW<
    enable_webui: true
    stop_napcat: false
    enable_update_check: false
    skip_setup: false
